version: "3.8"
services:
  neo4j:
    image: neo4j:5.16
    environment:
      NEO4J_AUTH: neo4j/neoreach123
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo 'RETURN 1' | cypher-shell -u neo4j -p neoreach123 > /dev/null",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  neoreach:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      - NEO4J_URL=${NEO4J_URL}
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}                                                                                                                                                                                                                                                                                                          
volumes:
  neo4j_data:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                